### ISSUE TITLE
cannot find test

### ISSUE THREAD

**Issue by woshiawang** [lyuchenyang/Dialogue-to-Video-Retrieval#1]
can you give me a line, including avsd_test.json and test_video? Thank you.

**Comment by lyuchenyang** [comment]
Hi, sorry for the confusion. Please check out this link for downloading the dataset: [avsd dataset](https://drive.google.com/file/d/1P9gmqJFsxuimp_BENLy0Tp98MdGqelIL/view?usp=sharing)
